# -*- coding: utf-8 -*-
"""brainrot_videogeneralas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17LprOR-h5mJphUjWl7MIdYeiTRb2EP21
"""

import os
from diffusers import StableDiffusionPipeline
from transformers import BlipProcessor, BlipForConditionalGeneration
from torchvision import models, transforms
from PIL import Image
import torch
from collections import Counter
import pandas as pd

# --- Mappa létrehozása frame-eknek ---
os.makedirs("frames", exist_ok=True)

# --- Pipeline setup ---
pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16
).to("cuda")

resnet = models.resnet18(pretrained=True)
resnet.eval()

processor = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-base")
blip_model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base")

preprocess = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

# --- Prompt lista ---
prompts = ["cat", "dog", "forest scene", "robot", "castle"]
results = []

# --- Kép generálás és feldolgozás ---
for i, prompt in enumerate(prompts):
    # Kép generálás
    img = pipe(prompt, guidance_scale=7.5).images[0]
    frame_path = f"frames/frame_{i:03d}.png"
    img.save(frame_path)

    # ResNet osztályozás
    input_tensor = preprocess(img).unsqueeze(0)
    with torch.no_grad():
        output = resnet(input_tensor)
    probs = torch.nn.functional.softmax(output[0], dim=0)
    top_prob, top_catid = torch.topk(probs, 3)

    # BLIP caption
    inputs = processor(img.convert("RGB"), return_tensors="pt")
    out = blip_model.generate(**inputs)
    caption = processor.decode(out[0], skip_special_tokens=True)

    # Eredmények mentése
    results.append({
        "frame": frame_path,
        "prompt": prompt,
        "caption": caption,
        "top_classes": top_catid.tolist(),
        "top_probs": top_prob.tolist()
    })

# --- Dataframe statisztika ---
df = pd.DataFrame(results)
df

import cv2

# Képek betöltése rendezett sorrendben
frames = sorted([f"frames/{f}" for f in os.listdir("frames") if f.endswith(".png")])
frame_example = cv2.imread(frames[0])
height, width, layers = frame_example.shape

# Videó létrehozása
video_name = "generated_video.mp4"
video = cv2.VideoWriter(video_name, cv2.VideoWriter_fourcc(*'mp4v'), 2, (width, height))  # 2 FPS

for f in frames:
    img = cv2.imread(f)
    video.write(img)

video.release()
print(f"Videó elkészült: {video_name}")