# -*- coding: utf-8 -*-
"""kutyus_generalo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QqRb292Q7irF4aw-_lvgEpMEgTOQQWj6
"""

from diffusers import StableDiffusionPipeline
import torch

model_id = "runwayml/stable-diffusion-v1-5"

pipe = StableDiffusionPipeline.from_pretrained(
    model_id,
    torch_dtype=torch.float16
).to("cuda")  # ha van NVIDIA GPU

prompt = "cat"
image = pipe(prompt, guidance_scale=7.5).images[0]

image.save("generated.png")

import torch
from torchvision import models, transforms
from PIL import Image

# Modell betöltése (előtanított)
model = models.resnet18(pretrained=True)
model.eval()

# Kép betöltése
img = Image.open("generated.png")

# Transform
preprocess = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

input_tensor = preprocess(img)
input_batch = input_tensor.unsqueeze(0)

with torch.no_grad():
    output = model(input_batch)

probabilities = torch.nn.functional.softmax(output[0], dim=0)

# Legvalószínűbb osztály
top_prob, top_catid = torch.topk(probabilities, 1)

print(top_catid)

from transformers import BlipProcessor, BlipForConditionalGeneration
from PIL import Image
import torch

processor = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-base")
model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base")

image = Image.open("generated.png").convert("RGB")

inputs = processor(image, return_tensors="pt")

out = model.generate(**inputs)
caption = processor.decode(out[0], skip_special_tokens=True)

print("Caption:", caption)